# SVD - Singular Value Decomposition

In [1]:
import numpy as np
np.random.seed(3) # setting random state as 3

In [2]:
# generating random matrix of size (3rows, 4 columns)

In [3]:
A = np.random.rand(3,4)

In [4]:
print A

[[ 0.5507979   0.70814782  0.29090474  0.51082761]
 [ 0.89294695  0.89629309  0.12558531  0.20724288]
 [ 0.0514672   0.44080984  0.02987621  0.45683322]]


# computing U, V and Singular Values

In [5]:
# finding A*A_{T}

In [6]:
AA_t = np.matmul(A, A.T)

In [8]:
print AA_t

[[ 1.15042208  1.26894005  0.58256071]
 [ 1.26894005  1.65941685  0.53947974]
 [ 0.58256071  0.53947974  0.40655137]]


In [9]:
print AA_t.shape

(3L, 3L)


In [14]:
# finding U through computing Eigen vector of AA_t

In [15]:
from numpy.linalg import eig

In [16]:
sig_U, U = eig(AA_t) 

In [17]:
print sig_U

[ 2.94337779  0.02943855  0.24357396]


In [18]:
print U

[[-0.61403062 -0.72019736  0.32292748]
 [-0.73145093  0.36550649 -0.57566009]
 [-0.29655678  0.58967853  0.75122121]]


In [19]:
print U.shape

(3L, 3L)


In [10]:
# finding A_{T}*A

In [11]:
A_tA = np.matmul(A.T,A)

In [12]:
print A_tA

[[ 1.10338147  1.21307577  0.27390839  0.4899316 ]
 [ 1.21307577  1.49912796  0.33173453  0.7488684 ]
 [ 0.27390839  0.33173453  0.10128983  0.18827728]
 [ 0.4899316   0.7488684   0.18827728  0.51259105]]


In [13]:
print A_tA.shape

(4L, 4L)


In [20]:
# finding V through computing Eigen vector of A_tA

In [21]:
sig_V, V = eig(A_tA) 

In [22]:
print sig_V

[  2.94337779e+00   2.43573956e-01   2.69494879e-16   2.94385504e-02]


In [23]:
print V

[[ 0.58673377  0.60280349 -0.48799584  0.23287654]
 [ 0.71177689 -0.08888163  0.53036265 -0.45187296]
 [ 0.16282317 -0.08933629  0.49145704  0.85086874]
 [ 0.35015105 -0.78787501 -0.48892278  0.13267148]]


In [24]:
print V.shape

(4L, 4L)


# finding U, V and Singular Values of a matrix using numpy

In [25]:
from numpy.linalg import svd

In [40]:
U_np, sig_np, V_np = np.linalg.svd(A, full_matrices=True)

In [28]:
print U_np

[[-0.61403062  0.32292748  0.72019736]
 [-0.73145093 -0.57566009 -0.36550649]
 [-0.29655678  0.75122121 -0.58967853]]


In [29]:
print U_np.shape

(3L, 3L)


In [32]:
print U # U found manually

[[-0.61403062 -0.72019736  0.32292748]
 [-0.73145093  0.36550649 -0.57566009]
 [-0.29655678  0.58967853  0.75122121]]


In [42]:
print np.sqrt(sig_U)

[ 1.71562752  0.17157666  0.49353212]


In [43]:
print V_np

[[-0.58673377 -0.71177689 -0.16282317 -0.35015105]
 [-0.60280349  0.08888163  0.08933629  0.78787501]
 [ 0.23287654 -0.45187296  0.85086874  0.13267148]
 [-0.48799584  0.53036265  0.49145704 -0.48892278]]


In [45]:
print V_np.shape

(4L, 4L)


In [46]:
print V

[[ 0.58673377  0.60280349 -0.48799584  0.23287654]
 [ 0.71177689 -0.08888163  0.53036265 -0.45187296]
 [ 0.16282317 -0.08933629  0.49145704  0.85086874]
 [ 0.35015105 -0.78787501 -0.48892278  0.13267148]]


In [47]:
print sig_np

[ 1.71562752  0.49353212  0.17157666]


In [48]:
print np.sqrt(sig_V)

[  1.71562752e+00   4.93532122e-01   1.64162992e-08   1.71576661e-01]
